version: '3.8'

services:
  cuto-public:
    build: .
    container_name: cuto-public
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    # Optional: Volumes f√ºr Logs
    # volumes:
    #   - ./logs:/app/logs

